# -*- coding: utf-8 -*-
"""사람 인식 모델 학습

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vf7rQmq739enlGZr95rfaY4vvQFTVYWv
"""

#구글 드라이브 연결

from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# 내 구글 드라이브로 이동
# %cd "/content/drive/MyDrive"

# %cd '/content/'

!git clone https://github.com/ultralytics/yolov5.git

!pip install -U -r yolov5/requirements.txt

import torch

#파이토치 버전 확인, cuda device properties 확인
print('torch %s %s' % (torch.__version__, torch.cuda.get_device_properties(0) if torch.cuda.is_available() else 'CPU'))

#오픈cv 버전 확인

import cv2
print(cv2.__version__)

# Commented out IPython magic to ensure Python compatibility.
#사진 가져오기

!mkdir datasets
# %cd /content/datasets/

!curl -L "https://universe.roboflow.com/ds/Gega6ATJkJ?key=2YG8UuuPNf" > roboflow.zip; unzip roboflow.zip; rm roboflow.zip

# Commented out IPython magic to ensure Python compatibility.
#test, train, valid 나누는 명령어 쓰기 위한 거였는데
#요즘 파일은 나눠져서 나오는듯
#그러면 10번코드 안쓰고 여기서 train, valid 리스트 만들어서
#txt 만들어도 될듯?

# %cd /

from glob import glob

train_img_list = glob('/content/datasets/train/images/*.jpg')
val_img_list = glob('/content/datasets/valid/images/*.jpg')

print(len(train_img_list))
print(len(val_img_list))

# from sklearn.model_selection import train_test_split

# train_img_list, val_img_list = train_test_split(img_list, test_size=0.2, random_state=2000)

print(len(train_img_list), len(val_img_list))

with open('/content/datasets/train.txt', 'w') as f:
  f.write('\n'.join(train_img_list) + '\n')
with open('/content/datasets/val.txt', 'w') as f:
  f.write('\n'.join(val_img_list) + '\n')

import yaml

with open('/content/datasets/data.yaml', 'r') as f:
  #data = yaml.load(f) 버전 바뀌고 명령어 바뀜
  data = yaml.full_load(f)
print(data)

data['train'] = '/content/datasets/train.txt'
data['val'] = '/content/datasets/val.txt'

with open('/content/datasets/data.yaml', 'w') as f:
  yaml.dump(data, f)

print(data)

# Commented out IPython magic to ensure Python compatibility.
#학습 마지막 이름 바꾸기

# %cd /content/yolov5/

!python train.py --img 416 --batch 16 --epochs 50 --data /content/datasets/data.yaml --cfg /content/yolov5/models/yolov5s.yaml --weights yolov5s.pt --name kids_yolov5s_results

#드라이브저장

!cp -r /content/yolov5/runs/train/kids_yolov5s_results /content/drive/MyDrive/models

# Commented out IPython magic to ensure Python compatibility.


# %cd /content/yolov5/

!python detect.py --source /content/drive/MyDrive/kids/test3.mp4 --weights /content/drive/MyDrive/models/weights/best.pt